version: 0.2
phases:
  install:
    runtime-version:
       runtime-versions:
         java: openjdk8
         docker: 18
 
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=862605034458.dkr.ecr.ap-southeast-1.amazonaws.com/codepipeline
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH}
      - echo Grant execute permission for gradlew
      - cd server
      - chmod 755 ./gradlew
      - echo Test
      - ./gradlew test
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo $IMAGE_TAG
 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Finish
      
      
