version: 0.2
phases:
  install:
    runtime-version:
         java: openjdk8
         docker: 18
 
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=862605034458.dkr.ecr.ap-southeast-1.amazonaws.com/codepipeline
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH}
      - echo Grant execute permission for gradlew
      - cd server
      - chmod 755 ./gradlew
      - echo Test
      - ./gradlew test
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo $IMAGE_TAG
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Finish
 
  post_build:
    commands:
      - echo 'Deploy to ec2'
      - echo 'Remote to ec2'
      - ssh -i "Codepipeline.pem" ubuntu@ec2-52-77-212-137.ap-southeast-1.compute.amazonaws.com
      - echo 'loginECR'
      - $sudo $(aws ecr get-login --no-include-email --region ap-southeast-1)
      - echo 'stop container'
      - docker rm -f $(docker ps -a -q)
      - echo Pull the Docker images to ec2
      - docker pull $REPOSITORY_URI:$IMAGE_TAG
      - echo 'start container'
      - docker run -d -p 9000:9000 $REPOSITORY_URI:$SHA
      - echo Finish
     
      


    
    

      
