version: 0.2
phases:
  install:
    runtime-version:
         java: openjdk8
         docker: 18
 
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=767272958636.dkr.ecr.ap-southeast-1.amazonaws.com/codepipeline
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Grant execute permission for gradlew
      - cd server
      - chmod 755 ./gradlew
      - echo Test
      - ./gradlew test
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd ..
      - docker-compose build
      - echo $IMAGE_TAG
  
      
 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker-compose push
      - echo 'Finish'
      
artifacts:
  type: zip
  files:
    - 'appspec.yml'
    - 'docker-compose.yml'
    - 'scripts/after_install.sh'
    - 'scripts/start_container.sh'
    - 'scripts/kill_container.sh'


    
    

      
