version: 0.2
phases:
  install:
    runtime-version:
       runtime-versions:
         java: openjdk8
 
  pre_build:
    commands:
      - echo Grant execute permission for gradlew
      - cd server
      - chmod 755 ./gradlew
      
  build:
    commands:
      - echo Building...
      - cd sever
      - ./gradlew test
      
